lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart
playground/lib/home/pages/sheet_page_with_lazy_list.dart
playground_navigator2/lib/modal/pages/sheet_page_with_lazy_list.dart

This PR prevents the Top bar motion caused by horizontal scrolling.
Reported in Issue #10 
| Before  | After |
| ------------- | ------------- |
|  <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/83c67173-7fe9-4012-b9c4-28bd01ab3338"> | <video src=https://github.com/woltapp/wolt_modal_sheet/assets/13782003/8d041403-0723-4f45-9ffd-b317631ce727> |

Prevent horizontal scroll in the main content causing top bar motion

---

lib/src/wolt_modal_sheet.dart
lib/src/wolt_modal_sheet_route.dart
playground/lib/home/home_screen.dart
playground_navigator2/lib/router/playground_router_delegate.dart
playground_navigator2/lib/router/router_pages/sheet_page.dart

This PR adds `onModalDismissedWithDrag` field to the `WoltModalSheetRoute` to detect the modal dismiss with drag gesture.
When using imperative API, it is enough to call `Navigator.of(context).pop()` to dismiss the modal. In fact, this is the default behavior when dismiss callbacks are not provided by the library users. However, using Navigator 2.0 requires actions in the callbacks to update the app state that builds the navigation stack on modal dismiss events.
In this screen recording from navigator2 playground example, it can be seen that the address bar is updated with both barrier tap and dismiss by frag events.
Note that earlier, this was handled in router delegate with Navigator's `onPop` callback. We no longer need to handle this imperatively in the Navigator widget.
<video …

Add callback for on modal dismiss with drag to be utilized in Navigator 2.0

---

coffee_maker/lib/home/online/store_online_content.dart
example/lib/main.dart
lib/src/wolt_modal_sheet.dart

`WoltModalSheet.show` method is a shortcut when the users of the library do not need a dynamically set page list builder. This is why we don't need a `ValueNotifier` for this method. This PR removes the `notifier` suffix to match this.

Rename page list builder notifier parameter for WoltModalSheet.show method

---

lib/src/content/components/main_content/wolt_modal_sheet_hero_image.dart

This PR modifies the `_HeroImageFlowDelegate` class to scale the image from the center instead of the top left corner.
The hero image was scaling from the top left corner and this was causing the image to look not-centered.
To fix this, we now scale the image from the center.
In the updated code, we calculate the `translationX` and `translationY` values to shift the image by half of the difference between the container size and the scaled image size. Then, we create a `Matrix4` object using `Matrix4.identity()` and apply both the scaling and translation using the `scale` and `translate` methods respectively. Finally, we pass the resulting `transformMatrix` to the `transform` property of `flowPaintingContext.paintChild`.
With this modification, the image should be scaled from the center …

Scale image from center in HeroImageFlowDelegate

---

lib/src/wolt_modal_sheet.dart
lib/src/wolt_modal_sheet_route.dart
playground_navigator2/lib/main.dart
playground_navigator2/lib/router/playground_router_delegate.dart
playground_navigator2/lib/router/router_pages/sheet_page.dart
playground_navigator2/pubspec.yaml

In many cases people don't care about responsiveness and just want to use the package right away. We should provide a built-in responsiveness that will speed up the onboarding. This PR does this by providing default breakpoint and modal type builder. 
The playground_nav2 example uses the default implementation.

Make modal type builder optional by providing default breakpoint and modal type builder

---

lib/src/wolt_modal_sheet.dart

This PR corrects the missing parameter input in the .show method and enables the onModalDismissedWithDrag callback to work.

Added missing onModalDismissedWithDrag parameter .show method

---

CHANGELOG.md

A common practice is to show the latest update of a package/project at the top. Otherwise, when the are a bunch of updates already, users will need to scroll down to the bottom to see the latest changes.

Rework the changelog to show the latest update at the top

---

coffee_maker/lib/home/online/modal_pages/add_water/water_settings_modal_page.dart
lib/src/content/components/main_content/wolt_modal_sheet_top_bar.dart
lib/src/content/components/main_content/wolt_modal_sheet_top_bar_title.dart
lib/src/modal_page/wolt_modal_sheet_page.dart
playground/lib/home/pages/root_sheet_page.dart
playground/lib/home/pages/sheet_page_with_lazy_list.dart
playground_navigator2/lib/modal/pages/root_sheet_page.dart
playground_navigator2/lib/modal/pages/sheet_page_with_lazy_list.dart
test/content/components/main_content/wolt_modal_sheet_top_bar_title_test.dart
test/widget_test_template.dart

Addresses issue: https://github.com/woltapp/wolt_modal_sheet/issues/26
In many cases, users of this library forget to provide top bar title assuming that their page will never be scrollable. This PR aims to improve the library's usability by providing a default `topBarTitle` widget using the `pageTitle`.
The key changes include:
* If topBarTitle not provided, the data of the pageTitle widget (if it is a Text widget) or the first direct "Text" child of the `pageTitle` widget will be used as the source of the data for the `topBarTitle` Text widget.
The following scrollable page produces the attached video. Note that `topBarTitle` is not provided and the source of the title is the descendent of the `pageTitle`:
```dart
WoltModalSheetPage.withCustomSliverList(
mainContentPadding: …
```

Use page title text by default as source of the top bar title when top bar title is not provided

---

test/wolt_modal_sheet_test.dart

This adds some `WoltModalSheet` tests.

Add some `WoltModalSheet` tests

---

example/pubspec.yaml
lib/src/content/components/main_content/wolt_modal_sheet_top_bar.dart
playground_navigator2/lib/router/playground_router_delegate.dart

Fixes the following linting warnings:
```shell
info • The imported package 'wolt_modal_sheet' isn't a dependency of the importing package • example/lib/main.dart:2:8 • depend_on_referenced_packages
info • The import of 'package:flutter/foundation.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' •
lib/src/content/components/main_content/wolt_modal_sheet_top_bar.dart:1:8 • unnecessary_import
warning • Unused import: 'package:wolt_modal_sheet/src/modal_page/wolt_modal_sheet_page.dart' • lib/src/content/components/main_content/wolt_modal_sheet_top_bar.dart:3:8 • unused_import
warning • Unused import: 'package:wolt_modal_sheet/src/utils/wolt_layout_transformation_utils.dart' • …
```

Fix linter violations

---

lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart

This PR changes the scroll physics so that the scroll offset is prevented from reaching beyond the bounds of the content in main scroll view
| Before  | After |
| ------------- | ------------- |
|  <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/fb9a6ecd-97ab-4fe7-bc03-08f43399d675"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/60823a83-9a45-44f8-8ba4-f515c4bbaf89"> |

Prevent the scroll offset from reaching beyond the bounds of the content in main scroll view

---

lib/src/content/wolt_modal_sheet_animated_switcher.dart
lib/src/content/wolt_modal_sheet_layout.dart
lib/src/modal_page/wolt_modal_sheet_page.dart
lib/src/theme/wolt_modal_sheet_default_theme_data.dart
lib/src/theme/wolt_modal_sheet_theme_data.dart
lib/src/wolt_modal_sheet.dart
lib/src/wolt_modal_sheet_route.dart
playground/lib/home/dynamic_page_properties.dart
playground/lib/home/home_screen.dart
playground/lib/home/pages/multi_page_path_name.dart
playground/lib/home/pages/root_sheet_page.dart
playground/lib/home/pages/sheet_page_with_dynamic_page_properties.dart

Don't merge this PR before #44 
This pull request introduces a new feature that enhances the behavior of the `WoltModalSheet` library by allowing the enabling or disabling of drag-to-dismiss functionality for the bottom sheet on a per-page basis. The primary change is the addition of the `enableDragForBottomSheet` property within the `WoltModalSheetPage` class.
- Added a new property `enableDragForBottomSheet` to the `WoltModalSheetPage` class.
- Enhanced the `WoltBottomSheetDragHandle` to be conditionally displayed based on the `enableDragForBottomSheet` property.
- Added a new use case to the `playground` example app to demonstrate how to dynamically enable/disable drag for modal sheet.
- Updated documentation and examples to demonstrate the usage of the new feature.
This feature …

Add option to dynamically enable bottom sheet drag for a single page

---

CHANGELOG.md
example/pubspec.lock
lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart
lib/src/content/components/main_content/wolt_modal_sheet_top_bar_title_flow.dart

Before releasing the v0.1.0;
- Updated the example project's dependency version
- Removed unnecessary imports

Remove unnecessary import and update example project's dependency version

---

CHANGELOG.md
README.md
example/pubspec.lock
pubspec.yaml

**Updates broken image links for pub.dev**
For pub.dev to display images we need to add `raw=true` to image links or use `https://raw.githubusercontent.com` kind a format

Prepare v0.1.2

---

lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart
lib/src/content/wolt_modal_sheet_layout.dart

Issue reported within #46 
This PR addresses an issue where an extra scrollbar was being displayed in web and desktop apps when a nested scroll view was present within a modal page constructed with `withSingleChild` factory method.
Wrapped the singleChildContent within a [ScrollConfiguration](https://api.flutter.dev/flutter/widgets/ScrollConfiguration-class.html) widget the copy of the parent scroll behavior and changed the scrollbars to false for the descendants.
| Before  | After |
| ------------- | ------------- |
|  <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/25342b62-2c29-4699-b253-9f5bf86d271e"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/1b3c937d-ae90-4562-b67a-fbe926e48245"> |

Remove extra scrollbars in the modal sheet due to nested scroll views

---

lib/src/wolt_modal_sheet.dart
test/wolt_modal_sheet_test.dart

fixes [Throw a helpful error when returning an empty list in `pageListBuilder`](https://github.com/woltapp/wolt_modal_sheet/issues/33)

Throw a helpful error message when returning an empty list in `pageListBuilder`

---

README.md
lib/src/content/components/main_content/wolt_modal_sheet_top_bar.dart
lib/src/content/wolt_modal_sheet_animated_switcher.dart
lib/src/modal_page/wolt_modal_sheet_page.dart
playground/lib/home/pages/multi_page_path_name.dart
playground/lib/home/pages/root_sheet_page.dart
playground/lib/home/pages/sheet_page_with_custom_top_bar.dart

Currently, the custom top bar widget operates exclusively when the `isTopBarLayerAlwaysVisible` is set to `true`. Setting this to `false` when custom top bar is used triggers an exception. This PR introduces the flexibility to enable the custom top bar to be used even when `isTopBarLayerAlwaysVisible` is set to `true`.
* When a `WoltModalSheetPage.topBar` widget is provided, it will be wrapped with shadow and elevation determined by the theme or default settings. Without a `WoltModalSheetPage.topBar,` a default top bar will be generated, styled according to the theme settings.
* For pages utilizing the default top bar, the title of the top bar will also be utilized. In contrast, pages with a custom top bar will omit the top bar title provided with `WoltModalSheetPage.topBarTitle`.
* An …

Allow custom top bar widget to be "not always visible"

---

coffee_maker/pubspec.yaml
demo_ui_components/pubspec.yaml
example/pubspec.yaml
lib/src/content/components/paginating_group/main_content_animated_builder.dart
playground/lib/home/pages/sheet_page_with_custom_top_bar.dart
playground/lib/home/pages/sheet_page_with_lazy_list.dart
playground/lib/home/pages/sheet_page_with_no_page_title_and_no_top_bar.dart
playground/pubspec.yaml
playground_navigator2/pubspec.yaml
pubspec.yaml
test/wolt_modal_sheet_test.dart

fixes [App cannot build on older Flutter verrsion - Throws `Error: Member not found: 'MediaQuery.sizeOf`](https://github.com/woltapp/wolt_modal_sheet/issues/76)
fixes [Update minimum supported Flutter version to `3.7.2`](https://github.com/woltapp/wolt_modal_sheet/issues/80)
This PR sets the minimum Flutter version to be `3.7.2` and matches the Dart SDK version bundled in this release. 
It means a users should have at least Flutter `3.7.2` installed.
- Updated APIs to be compatible to with this requirement
- Replaced `SearchBar` with `IconButton` in playground as it doesn't exist in `3.7.2`
- Updated a test to use older API

Update the package & examples to support minimum Flutter `v3.7.2`

---

CHANGELOG.md
pubspec.yaml

This release addresses the issue that prevented the use of app for the versions before 3.10.0.

Prepare for 0.1.4 release

---

lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart
playground/lib/home/pages/sheet_page_with_dynamic_page_properties.dart

When the top bar is set to always visible, the overflow scroll effect from the leading side (top part) will not be visible since the custom scroll view is placed and starts behind the top bar.
This PR adds explicit padding to the custom scroll view when `isTopBarLayerAlwaysVisible` is set to `true`. 
This is how all the pages look after the fix:
https://github.com/woltapp/wolt_modal_sheet/assets/13782003/17304900-f7bc-468a-8815-98938db1df28
* https://github.com/woltapp/wolt_modal_sheet/issues/102
- [-] Yes, this is a breaking …

Fix overflow scroll effect visibility when top bar is always visible

---

lib/src/widgets/wolt_bottom_sheet_drag_handle.dart

We are trying to read `MaterialLocalizations.of(context).modalBarrierDismissLabel` which is not there for Cupertino apps. In this fix;
- We first try to read it from `MaterialLocalizations`,
- If not available, try to read it from `CupertinoLocalizations`,
- If that is also not available, return the default label from `DefaultMaterialLocalizations`.
Note: Test cases will be added after we decide which mocking package to use.
https://github.com/woltapp/wolt_modal_sheet/issues/61 …

Fix 'No MaterialLocalizations found' exception for Cupertino apps

---

playground_navigator2/lib/modal/pages/sheet_page_with_lazy_list.dart

This PR fixes a `RangeError` appearing on the `SheetPageWithLazyList` of the `playground_navigator2 `.
Fixes: https://github.com/woltapp/wolt_modal_sheet/issues/117

Fix `RangeError` on the `SheetPageWithLazyList` of the `playground_navigator2 `.

---

lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart
lib/src/content/components/main_content/wolt_modal_sheet_top_bar_flow.dart
lib/src/content/components/main_content/wolt_modal_sheet_top_bar_title_flow.dart
lib/src/content/wolt_modal_sheet_animated_switcher.dart
lib/src/utils/soft_keyboard_closed_event.dart
playground/lib/home/pages/sheet_page_with_text_field.dart
pubspec.yaml

This PR fixes the top bar widget visibility issue due to keyboard closing event (#96) by introducing a new feature in the form of a value notifier, specifically designed to detect the dismissal of the soft-keyboard. This PR primarily impacts two components: `WoltModalSheetTopBarFlow` and `WoltModalSheetTopBarTitleFlow`.
The primary goal of this implementation is to trigger a re-paint in the top bar components when the soft-keyboard is closed. This is essential to prevent the top bar from being stuck unresponsive after the keyboard's closing phase.
When `isTopBarAlwaysVisible` is set to false (by default), the visibility and appearance of the top bar and top bar title are synchronized with the scroll controller's position. Both `WoltModalSheetTopBarFlow` and `WoltModalSheetTopBarTitleFlow` …

[Issue-96] Fix TopBar Widget keeps being visible after Keyboard hides

---

README.md
coffee_maker/lib/home/online/widgets/coffee_order_list_item_tile.dart
coffee_maker/lib/main.dart

Our all example apps are uses `MaterialApp` at the top level, we are switching to `CupertinoApp` in `coffee_maker` example to also demonstrate that.
Before | After
:-:| :-:
<video src=https://github.com/woltapp/wolt_modal_sheet/assets/7239330/f2801497-e255-4dfe-a8bd-97a48624a680 width=180/> | <video src=https://github.com/woltapp/wolt_modal_sheet/assets/7239330/5994ee7f-1ec7-4aef-9b5b-05572d88c4fd width=180/>
https://github.com/woltapp/wolt_modal_sheet/issues/61 …

Convert MaterialApp example app to CupertinoApp

---

lib/src/content/wolt_modal_sheet_animated_switcher.dart

This Pull Request introduces an improvement to the state management within the WoltModalSheet package. Specifically, it addresses the scenario where the state update does not reflect on the modal sheet page due to unchanged page index yet with a new widget set provided.
Previously, when the root decorator widget, typically utilized as a ChangeNotifierProvider, updated the state, the new set of widgets associated with the same page index did not update the UI as expected. This was because the internal mechanism did not adequately mark the new widget set as "dirty" for rendering.
To resolve this, the PR implements a strategy where the incoming widget set is explicitly set to null following a state change. Subsequently, it forcibly rebuilds the current page set with the updated widgets. This …

Fix state update handling: Current page widgets do not receive update if the decorator marks the page as dirty

---

example/lib/main.dart

Issue reported within #91
If we copied the `wolt_modal_bottom` sheet directly instead of cloning the example from `pub.dev`, an error would occur because we did not import the assets but only the code. That's why I decided to pull the example from the `github repo` instead of getting the `assets` from local. (This bug was solved before, but I solved it again because it did not fit the guidle.)
<p align="center">
<table>
<tr>
<th style="text-align: center">Error</th>
<th style="text-align: center">Fixed</th>
</tr>
<tr>
<td style="text-align: center">
</td>
<td style="text-align: center">
</td>
</tr>
</table>
</p>
fix #91
This will ensure a smooth and quick review …

Update hero image in the pub dev example

---

lib/src/content/wolt_modal_sheet_animated_switcher.dart

This reverts commit 002f2c2a97f1c6dd32df04f2d6342bae731bc048.
This PR revert addresses the issues #134 #135

Revert "fix-page-widgets-not-marked-as-dirty-when-decorator-updates"

---

CHANGELOG.md
pubspec.yaml

We are reverting https://github.com/woltapp/wolt_modal_sheet/commit/002f2c2a97f1c6dd32df04f2d6342bae731bc048 to fix issue reports [#134](https://github.com/woltapp/wolt_modal_sheet/issues/134) and [#135](https://github.com/woltapp/wolt_modal_sheet/issues/135)
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/woltapp/wolt_modal_sheet/issues). Indicate, which of these issues are resolved or fixed by this PR.* …

Prepare v0.4.1

---

lib/src/theme/wolt_modal_sheet_default_theme_data.dart
lib/src/theme/wolt_modal_sheet_theme_data.dart

This PR updates the default clip behavior of the WoltModalSheet from Clip.antiAlias to Clip.antiAliasWithSaveLayer. The change addresses a rendering issue where a thin border was visible at the top bar of the modal sheet, which was not the intended design.
Modified the clipBehavior getter in WoltModalSheetThemeData to return Clip.antiAliasWithSaveLayer instead of Clip.antiAlias.
| antiAlias Vs antiAliasWithSaveLayer |
|--------|
| <img src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/9f12c073-63a1-44ac-b9a6-439147acef59"> |
| <img src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/62153fdd-9183-4cf3-bc45-9c8e7aaef784"> | 
https://github.com/woltapp/wolt_modal_sheet/issues/162
Before you create this PR confirm that it meets all requirements listed below by …

Change Default Clip Behavior to antiAliasWithSaveLayer to fix Top Bar rendering issue

---

example/.gitignore
example/.metadata
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Flutter/Debug.xcconfig
example/ios/Flutter/Release.xcconfig
example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner.xcworkspace/contents.xcworkspacedata
example/ios/Runner/Info.plist
example/ios/RunnerTests/RunnerTests.swift
example/macos/Flutter/Flutter-Debug.xcconfig
example/macos/Flutter/Flutter-Release.xcconfig
example/macos/Podfile
example/macos/Podfile.lock
example/macos/Runner.xcodeproj/project.pbxproj
example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/macos/Runner.xcworkspace/contents.xcworkspacedata
example/macos/Runner/Configs/AppInfo.xcconfig
example/macos/Runner/MainFlutterWindow.swift
example/macos/RunnerTests/RunnerTests.swift
example/test/widget_test.dart

Fixes [`wolt_modal_sheet/example` fails to run on iOS](https://github.com/woltapp/wolt_modal_sheet/issues/153)

Update `example` app files for missing `RunnerTests` folder and Podfile

---

lib/src/modal_page/non_scrolling_wolt_modal_sheet_page.dart
lib/src/modal_page/sliver_wolt_modal_sheet_page.dart
lib/src/modal_page/wolt_modal_sheet_page.dart
lib/src/theme/wolt_modal_sheet_default_theme_data.dart
lib/src/theme/wolt_modal_sheet_theme_data.dart
lib/src/wolt_modal_sheet.dart
playground/lib/home/pages/sheet_page_with_text_field.dart

This PR introduces a new flag, `resizeToAvoidBottomInset`, to the `WoltModalSheetPage`. This enhancement addresses an issue (https://github.com/woltapp/wolt_modal_sheet/issues/154). With this change, developers can now choose whether the `WoltModalSheet.mainContent` should resize when the onscreen keyboard appears, preventing it from shifting up and down.
To address this problem, we have added the `resizeToAvoidBottomInset` flag to the WoltModalSheetPage. This flag allows developers to specify whether the main content of the modal sheet should be resized to avoid being obscured by the keyboard. Internally, WoltModalSheet uses a Scaffold widget to implement this functionality. The flag's default value is sourced from [WoltModalSheetDefaultThemeData.resizeToAvoidBottomInset], and set to …

Add resizeToAvoidBottomInset Option to WoltModalSheet to Control Keyboard Overlay Behavior

---

.github/workflows/checks.yml
pubspec.yaml

fixes [Add PR check for tests](https://github.com/woltapp/wolt_modal_sheet/issues/190) (Second attempt)
1. Fix stuck checks.
2. Update checks to use flutter-action to use Flutter version from `pubpec.yaml`
3. Fix typos
Used https://marketplace.visualstudio.com/items?itemName=me-dutour-mathieu.vscode-github-actions to catch issues @ulusoyca 

Update PR checks

---

.github/workflows/firebase-hosting-pull-request.yml

Normally, when you generate PR deployment .yaml file from cli, it comes with on:pull_request. However, if there is a PR coming from the forked repos, github-action does not allow the incoming PR to reach the secrets and cannot receive firebase deployment information. For this reason, I changed pull_request to pull_request_target in the old PR and it could now access the secrets, but the problem this caused was now working in the codes on the deployment main. I missed this while making the last contribution. Currently, I checkout the incoming PR and then deploy. I tested it on my own repos and it works.
sample repository: https://github.com/AcarFurkan/workflow_trial …

Update PR deployment method

---

lib/src/wolt_modal_sheet.dart

This narrows the part of the tree on to which the user-provided decorator function is applied to to just the modal, instead of also wrapping the barrier.
- #201

fix: only decorate the content of the modal

---

lib/src/wolt_modal_sheet.dart
playground/lib/home/pages/sheet_page_with_dynamic_page_properties.dart

This PR introduces the `updateCurrentPage` method to the WoltModalSheet widget, offering a way to update the currently visible modal sheet page without triggering pagination animations. Currently, the `WoltModalSheetPage` class is not widget, and this makes it difficult to update the non-widget configuration of the currently visible page. This method enables replacing the page completely with a new configuration.
- Fixes https://github.com/woltapp/wolt_modal_sheet/issues/205
<video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/cbb4217b-6e1d-41c5-b117-4edae74d5301">
Does your PR require plugin users …

Introduce updateCurrentPage method to update the currently visible page without pagination animation

---

.firebaserc
.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml
.gitignore
README.md
firebase.json

This PR introduces an example deploy of using the coffee maker navigator 2 in conjunction with Firebase Deploy. The existing behavior did not include an example deploy of how to integrate the coffee maker navigator 2.

Add coffee maker navigator 2 example to Firebase Deploy

---

playground_navigator2/lib/modal/pages/root_sheet_page.dart

Every time the page was built on selection, the value notifier was reset to false. This PR fixes this issue by moving the enable notifier outside of the build method as static final field.
<video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/65ae2f03-98ab-4801-8071-6fcd21e29875">

Fix navigator_2_playground_example by Use static value notifier for button enabled listener

---

coffee_maker_navigator_2/lib/ui/add_water/view/widgets/add_water_screen.dart
coffee_maker_navigator_2/lib/ui/auth/view/auth_screen.dart
coffee_maker_navigator_2/lib/ui/orders/view/modal_pages/grind/grind_or_reject_modal_page.dart
coffee_maker_navigator_2/lib/ui/orders/view/modal_pages/grind/reject_order_modal_page.dart
coffee_maker_navigator_2/lib/ui/orders/view/orders_screen.dart
coffee_maker_navigator_2/lib/ui/orders/view/widgets/coffee_order_list_view_for_step.dart
coffee_maker_navigator_2/lib/ui/router/entities/app_route_page.dart
coffee_maker_navigator_2/lib/ui/router/entities/app_route_settings_name.dart
coffee_maker_navigator_2/lib/ui/router/entities/router_view_model_state.dart
coffee_maker_navigator_2/lib/ui/router/view/app_router_delegate.dart
coffee_maker_navigator_2/lib/ui/router/view_model/router_view_model.dart
coffee_maker_navigator_2/lib/ui/tutorials/view/single_tutorial_screen.dart
coffee_maker_navigator_2/lib/ui/tutorials/view/tutorials_screen.dart

This PR improves the coffee maker demo app implementation and UI:
1. Removes unnecessary selected bottom navigation bar information inside the OrdersScreenPage
2. Adds an example of how to add a modal sheet route with multiple pages in declarative way.
3. Adjust the UI to the large screen so that it works better on Web.
https://github.com/woltapp/wolt_modal_sheet/issues/189
<video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/82095951-273c-49e5-a545-9a5e34902392"> …

Improve coffee maker demo example

---

lib/src/modal_page/sliver_wolt_modal_sheet_page.dart
lib/src/theme/wolt_modal_sheet_default_theme_data.dart
lib/src/theme/wolt_modal_sheet_theme_data.dart
pubspec.yaml

These fixes are needed to get full points at pub.dev. Here is the list of changes:
- Removed unnecessary template tag
- Removed the following pubspec yaml issues:
```
* Your dependency on "flutter_keyboard_visibility" should have an upper bound. For example:
dependencies:
flutter_keyboard_visibility: ^6.0.0
Without an upper bound, you're promising to support all future versions of flutter_keyboard_visibility.
* The Flutter constraint should not have an upper bound.
In your pubspec.yaml the constraint is currently `3.10.6`.
You can replace that with just the lower bound: `>=3.10.6`.
```

Fix dart publish dry run issues

---

demo_ui_components/lib/src/selection_list/wolt_selection_list.dart
demo_ui_components/lib/src/selection_list/wolt_selection_list_tile.dart
playground/lib/home/pages/root_sheet_page.dart

fixes [`WoltSelectionListTile` has asymmetrical default padding](https://github.com/woltapp/wolt_modal_sheet/issues/220)
https://github.com/woltapp/wolt_modal_sheet/assets/48603081/3a5b70c5-bb45-40d3-88eb-5ff4c03f139e
https://github.com/woltapp/wolt_modal_sheet/assets/48603081/b81b0413-e186-498f-8218-ea3a8132a8ef

Fix `WoltSelectionListTile` default padding and divider height in playground example

---

lib/src/wolt_modal_sheet.dart
test/wolt_modal_sheet_test.dart

The `pageListBuilderNotifier` listener should have been disposed properly when the widget is demounted. This causes issues when you launch the modal sheet in the second time. This error is easily reproducible thanks to the well documented issue https://github.com/woltapp/wolt_modal_sheet/issues/226
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/c6b86418-80bb-469f-9d7b-adc208f0e8c7"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/e3381318-9fb3-4983-b95a-dc7e46ac46b8"> | 
https://github.com/woltapp/wolt_modal_sheet/issues/226 …

Dispose value notifier in WoltModalSheet

---

coffee_maker/lib/home/online/modal_pages/add_water/add_water_description_modal_page.dart
coffee_maker/lib/home/online/modal_pages/grind/grind_or_reject_modal_page.dart
coffee_maker/lib/home/online/modal_pages/ready/offer_recommendation_modal_page.dart
coffee_maker_navigator_2/lib/ui/orders/view/modal_pages/grind/grind_or_reject_modal_page.dart
coffee_maker_navigator_2/lib/ui/orders/view/modal_pages/ready/offer_recommendation_modal_page.dart
demo_ui_components/lib/src/button/wolt_elevated_button.dart
demo_ui_components/lib/src/colors/wolt_colors.dart
lib/src/modal_type/wolt_modal_type.dart
lib/src/widgets/wolt_modal_sheet_content_gesture_detector.dart
lib/wolt_modal_sheet.dart
playground/android/app/build.gradle
playground/lib/home/custom_sheets/floating_bottom_sheet_type.dart
playground/lib/home/custom_sheets/top_notification_sheet_type.dart
playground/lib/home/home_screen.dart
playground/lib/home/pages/custom_sheet_pages/adjust_time_notification_page.dart
playground/lib/home/pages/custom_sheet_pages/new_order_notification_page.dart
playground/lib/home/pages/custom_sheet_pages/reject_order_notification_page.dart
playground/lib/home/pages/sheet_page_with_no_page_title_and_no_top_bar.dart
playground/lib/main.dart

This PR adds two examples for adding custom modal types:
| Floating Bottom Sheet Type |
|--------|
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/e54f550b-9968-491d-8ad5-b3ef57bded2d"> |  
| Top Notification Sheet Type |
|--------|
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/5af58fa5-cd15-41e3-af3e-e5245907b856"> |  
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/woltapp/wolt_modal_sheet/issues). Indicate, which of these issues are resolved or fixed by this PR.*
Does your PR require plugin users to …

Add custom modal type examples to the playground app

---

lib/src/modal_type/wolt_alert_dialog_type.dart
lib/src/modal_type/wolt_dialog_type.dart
lib/src/modal_type/wolt_side_sheet_type.dart
lib/src/theme/wolt_modal_sheet_default_theme_data.dart
lib/src/utils/wolt_breakpoints.dart

This PR introduces **Breakpoint** system of **Wolt Design System** to this package. 
Also fixes dialog and alert dialog layout calculations.
| Dialog Before | Dialog After |
|<video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/d682b3f6-a7ac-4221-a799-5c50b722dd45"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/9d2dfe4d-973d-48fc-8912-52f6690b117d"> | 
| Alert Dialog Before | Alert Dialog After |
|<video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/35ce3587-cbbc-44a2-9873-13282c738f5a"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/ba6be55c-606a-4664-b577-d0df1f33d21d"> | 
Before you create this PR confirm that it meets all requirements listed below by …

Introduce: Breakpoints and fix dialog layout calculations

---

lib/src/modal_type/wolt_alert_dialog_type.dart
lib/src/modal_type/wolt_bottom_sheet_type.dart
lib/src/modal_type/wolt_dialog_type.dart
lib/src/modal_type/wolt_modal_type.dart
lib/src/modal_type/wolt_side_sheet_type.dart
lib/src/wolt_modal_sheet_route.dart
playground/lib/home/custom_sheets/top_notification_sheet_type.dart
playground/lib/home/home_screen.dart

This PR addresses an issue where alert dialogs could be dismissed by tapping the barrier (the area outside the dialog). This behavior was unintended for alert dialogs, which typically require explicit user action to dismiss.
| Before Dismiss on Barrier | After Dismiss on Barrier|
| <video src= "https://github.com/woltapp/wolt_modal_sheet/assets/13484562/73ae450a-3ded-420d-9106-86ce9144e281"> | <video src= "https://github.com/woltapp/wolt_modal_sheet/assets/13484562/b49a4b5d-b796-470a-91fc-24934f9a292a"> |

Fix: Prevent dismiss on barrier tap for alert dialog

---

lib/src/modal_type/wolt_dialog_type.dart

This PR adds position animations for dialogs when they appear and disappear. The animation creates a more polished and engaging user experience by adding a slight vertical movement to the dialog. This was added according to Wolt Design System.
| Before Dialog | After Dialog |
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/955b87d5-e72a-4524-ae0a-d7692486225a"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/6d71e121-2f0d-47c5-bfcd-aa9380a82a2b"> |
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/9e0d1168-567b-4cda-b67c-faf777354f65"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13484562/f4ac7eeb-995e-42da-9e66-5bdd6ac3ad6e"> | 
Before you create this PR confirm that it …

Fix: Wolt dialog type position animation updated

---

README.md

Adjustment: Readme updated for version 0.7.0 part 2

---

lib/src/modal_type/wolt_dialog_type.dart

After design review with motion designer at Wolt, we decided to adjust the enter animation y-position distance. It is longer distance now.
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/519865ab-d2db-4d7b-bbbd-8d8c00608c6d"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/c1d11150-1c98-47da-9abf-59bf28230f71"> |

Adjust dialog enter animation distance

---

lib/src/modal_type/wolt_bottom_sheet_type.dart
lib/src/modal_type/wolt_side_sheet_type.dart

closeProgressThreshold is currently only available in WoltModalType class. Extending the defined modal types do not allow overriding this value. We should add this value to constructor of WoltBottomSheetType class
[Add closeProgressThreshold to default modal type constructor methods](https://github.com/woltapp/wolt_modal_sheet/issues/253)
- x ] I updated/added relevant documentation (doc comments with `///`).

Feature: Extend close progress threshold for different types

---

lib/src/modal_type/wolt_bottom_sheet_type.dart
lib/src/modal_type/wolt_dialog_type.dart
playground/lib/home/pages/modal_page_name.dart
playground/lib/home/pages/root_sheet_page.dart
playground/lib/home/pages/sheet_page_with_min_height.dart

Dialog and bottom sheet min height is not respected to modal constraints. We added this test case to playground app.
The root cause is that the modal content constraints are calculated without consideration of the available space and it is independent of the modal constraints. When the min height is more than the content height, we currently don't fill the space to min height. It could be added as a feature in later updates, but adding this feature now will complicate the internal implementation. We can address this issue when we use the page as widget.
| <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/372e5dc2-2cc9-40c1-865f-638c5daca5ee"> | <video src="https://github.com/woltapp/wolt_modal_sheet/assets/13782003/5545b2bc-ddab- …

Fix: Dialog and bottom sheet minimum height is not respected to modal content min height

---

README.md

Updated the ReadMe with links to source of the example apps
fix: [Add links to repositories in ReadMe for showcase apps](https://github.com/woltapp/wolt_modal_sheet/issues/263)

Adjustment: Readme added source codes of example projects

---

coffee_maker_navigator_2/lib/ui/orders/view/widgets/coffee_order_list_view_for_step.dart
coffee_maker_navigator_2/lib/ui/router/entities/app_route_page.dart
lib/src/wolt_modal_sheet.dart
lib/src/wolt_modal_sheet_route.dart
playground_navigator2/lib/router/router_pages/sheet_page.dart

In order to stay consistent with the Router API of Flutter, we should rename routeSettings field as [settings](https://api.flutter.dev/flutter/widgets/Route/settings.html) field.
fix: [Rename [WoltModalSheetRoute.routeSettings] fields as [WoltModalSheetRoute.settings]](https://github.com/woltapp/wolt_modal_sheet/issues/198)

Adjustment: Renamed WoltModalSheetRoute routeSettings to settings

---

README.md
coffee_maker/lib/home/online/modal_pages/add_water/add_water_description_modal_page.dart
coffee_maker/lib/home/online/modal_pages/add_water/water_settings_modal_page.dart
coffee_maker/lib/home/online/modal_pages/grind/grind_or_reject_modal_page.dart
coffee_maker/lib/home/online/modal_pages/grind/reject_order_modal_page.dart
coffee_maker/lib/home/online/modal_pages/ready/offer_recommendation_modal_page.dart
coffee_maker/lib/home/online/modal_pages/ready/serve_or_offer_modal_page.dart
coffee_maker/lib/home/online/store_online_content.dart
coffee_maker_navigator_2/lib/ui/orders/view/widgets/coffee_order_list_view_for_step.dart
lib/src/modal_type/wolt_modal_type.dart
lib/src/wolt_modal_sheet.dart
lib/src/wolt_modal_sheet_route.dart
test/wolt_modal_sheet_test.dart

This PR refactors the modal decoration mechanism to separate the decoration of the modal barrier + content from the decoration of the content only. This also aligns it with the WoltModalType class methods, and resolves the existing issue with the decorator context (see [comment](https://github.com/woltapp/wolt_modal_sheet/pull/203#issuecomment-2222520519)). 
Methods in `WoltModalType` class: `decoratePageContent` and `decorateModal`:
```dart
/// Applies additional decorations to the modal page content.
///
/// This method can be overridden to provide custom decorations such as safe area padding
/// adjustments inside the modal page content. By default, it does not apply any decoration.
/// See the [WoltBottomSheetType] for an example of how overriding this method could be used to
/// fill …
```

[Breaking Change] Introduce modal and page content decorators

---

playground/lib/home/custom_sheets/attached_floating_bottom_sheet_type.dart
playground/lib/home/home_screen.dart

Adding an AttachedFloatingBottomSheetType to the Playground App.
This works by using a `GlobalKey` as the anchor to Align the Sheet at the Position of the Anchor.
One thing I think can still be improved is the animation. Ideally it would be nice if the Modal Scales out from the anchor position (+ Transformation based on Anchor Size/Alignment)
A Demo (before improvements to the Alignments/Size Constraints can be found here:
https://github.com/user-attachments/assets/9b1f6b7c-4a64-46c8-9eae-91cce0d5893d …

feat: Add Attached Sheet to Playground

---

lib/src/wolt_modal_sheet.dart
melos.yaml
test/wolt_modal_sheet_state_test.dart
test/wolt_modal_sheet_test.dart

This PR fixes existing broken tests

Fix existing state tests

---

lib/src/content/components/paginating_group/main_content_animated_builder.dart
lib/src/content/components/paginating_group/wolt_modal_sheet_page_transition_state.dart

ThisPR introduces support for both Left-to-Right (LTR) and Right-to-Left (RTL) text directions in the slide animation logic for modal sheet page transitions. The mainContentSlidePosition method is updated to handle different slide directions based on a new `isLTR` parameter. 
Calculated directionMultiplier based on `isLTR` and `isForwardMove` to correctly adjust the animation direction.
For LTR (isLTR = true), the multiplier is 1 for forward moves and -1 for backward moves.
For RTL (isLTR = false), the multiplier is -1 for forward moves and 1 for backward moves.
| Before LTR | After LTR |
| <video src="https://github.com/user-attachments/assets/842edbdb-6a06-4b6a-b512-696eda3ee86f"> | <video src="https://github.com/user-attachments/assets/7ee80d5f-74f1-4d25-be76-fe7e0da …

Fix: Consider directionality for pagination animation

---

pubspec.yaml

This PR adds the screenshots and topics meta for pubspec file. Here is the rules: [screenshots](https://dart.dev/tools/pub/pubspec#screenshots) & [topics](https://dart.dev/tools/pub/pubspec#topics)
Fixes https://github.com/woltapp/wolt_modal_sheet/issues/255

Add topics and screenshots to pubspec.yaml

---

coffee_maker_navigator_2/lib/ui/orders/view/modal_pages/ready/offer_recommendation_modal_page.dart
lib/src/content/components/main_content/wolt_modal_sheet_main_content.dart
lib/src/modal_page/sliver_wolt_modal_sheet_page.dart

Removes the previously marked as deprecated mainContentSlivers in favor of `mainContentSliversBuilder` field.
```dart
SliverWoltModalSheetPage(
mainContentSlivers: [
SliverList(
delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
// Your list items
}),
),
// Other sliver widgets...
],
// Additional page elements like pageTitle, topBarTitle, etc.
)
```
```dart
SliverWoltModalSheetPage(
mainContentSliversBuilder: (context) => [
SliverList(
delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
// Your list items
}),
),
// Other sliver widgets...
],
// Additional page elements like pageTitle, topBarTitle, etc.
)
```
This will ensure …

Remove deprecated mainContentSlivers field in SliverWoltModalSheetPage

---

README.md

Fixes the image linked to the deleted branch not visible in Readme file.
| <img width="673" alt="image" src="https://github.com/user-attachments/assets/b0644750-6708-4787-be8d-903653fa2cec"> | <img width="937" alt="image" src="https://github.com/user-attachments/assets/8ca84823-7c25-4d4b-9611-9159101d80ab"> | 
Also removed the Sample Apps section, and added the link to the web app to each sub section.

Fix screenshot of the example app in the ReadMe

---

demo_ui_components/lib/demo_ui_components.dart
demo_ui_components/lib/src/button/wolt_modal_sheet_close_or_next_sab.dart
lib/src/wolt_modal_sheet.dart
playground/lib/home/pages/root_sheet_page.dart
playground/lib/home/pages/sheet_page_with_custom_top_bar.dart
playground/lib/home/pages/sheet_page_with_forced_max_height.dart
playground/lib/home/pages/sheet_page_with_hero_image.dart
playground/lib/home/pages/sheet_page_with_in_app_navigation.dart
playground/lib/home/pages/sheet_page_with_lazy_list.dart
playground/lib/home/pages/sheet_page_with_min_height.dart
playground/lib/home/pages/sheet_page_with_no_page_title_and_no_top_bar.dart
playground/lib/home/pages/sheet_page_with_text_field.dart
playground/lib/home/pages/sheet_page_with_update_page_method.dart
test/wolt_modal_sheet_test.dart

This PR introduces new getter methods to the `WoltModalSheet` to get the current page and current page list.
- `pages`: Returns the list of pages currently in the modal sheet.
- `currentPage`: Retrieves the current page being displayed in the modal sheet.
- `currentPageIndex`: Provides the index of the currently displayed page within the navigation stack.
- `isAtFirstPage`: Returns true if the current page is the first in the stack, otherwise false.
- `isAtLastPage`: Returns true if the current page is the last in the stack, otherwise false.
#297 
New widget tests have been added to verify the correctness of these getter methods. The playground app also now shows the current page index, and total number of pages utilising these methods.
<video …

Expose page list, current page, and getters for isAtLastPage / isAtFirstPage

---

lib/src/content/wolt_modal_sheet_animated_switcher.dart
lib/src/utils/wolt_keyboard_closure_listener_mixin.dart
pubspec.yaml

This PR introduces the `WoltKeyboardClosureListenerMixin` mixin and removes the [FlutterKeyboardVisibility](https://github.com/MisterJimson/flutter_keyboard_visibility) package dependency. The purpose of this mixin is to track the visibility of the soft keyboard by monitoring the changes in the system's view insets and using the WidgetsBindingObserver.
- Utilizes the WidgetsBindingObserver to listen to changes in UI metrics, specifically to detect keyboard appearance and disappearance.
- Updates a ValueNotifier<SoftKeyboardClosedEvent> with a new event ID whenever the keyboard closes. This is important for widgets that need to adjust their layout or perform specific actions when the keyboard is hidden. For example, re-painting the top bar and top bar title.
| Android | iOS | …

Remove KeyboardVisibilityListener dependency and add WoltKeyboardClosureListenerMixin

---

test/wolt_modal_sheet_test.dart

Related [Prepare repository for tests requirement](https://github.com/woltapp/wolt_modal_sheet/issues/211)

Add `WoltModalSheet.modalBarrierColor` tests

---

README.md
demo_ui_components/lib/src/theme_data/app_theme_data.dart
example/lib/main.dart
playground/lib/main.dart
playground_navigator2/lib/main.dart

This PR updates the example app and demonstrates how to handle the area behind the sticky action bar in sliver list.
https://github.com/woltapp/wolt_modal_sheet/issues/305
<video src="https://github.com/user-attachments/assets/9b7aff40-2f5b-46ef-bfb8-0422e2006c2f">

[Example app] Add sliver padding to bottom to demonstrate how to show the area behind the sticky action bar

---

.github/workflows/tests_check.yml
CONTRIBUTING.md
melos.yaml

Fixes [Prepare repository for tests requirement](https://github.com/woltapp/wolt_modal_sheet/issues/211)
- Add a missing tests check will. comment on the PR if the tests are missing
-  Added `melos` command to run tests on the root and samples
- Updated `CONTRIBUTING.md` for writing tests

Add a missing tests check and update `CONTRIBUTING.md`

---

coffee_maker_navigator_2/lib/features/orders/data/remote/orders_remote_data_source.dart
coffee_maker_navigator_2/lib/features/orders/data/repository/orders_repository.dart
coffee_maker_navigator_2/lib/features/orders/di/orders_dependency_container.dart
coffee_maker_navigator_2/lib/features/orders/domain/orders_service.dart
coffee_maker_navigator_2/lib/features/orders/ui/view_model/orders_screen_view_model.dart

This PR prepares the coffee maker navigator 2.0 demo app for the workshop which will be held in Flutter&Friends.
Changes:
- Simulate polling with 3 seconds interval for the fetching of the coffee orders.

[Coffee Maker Example App] Simulate polling for fetching coffee orders

---

lib/src/widgets/wolt_modal_sheet_drag_to_dismiss_detector.dart

I'm sorry for the failed first attempt. I'm not really used to doing this. I hope everything is fine now.
I fixed the issue with the GestureDetector's onDrag callback in the WoltModalSheetDragToDismissDetector.
Previously, the callbacks were not properly set to null when they needed to be disabled, which caused them to remain active unintentionally.
This is realated to issue #322

fix gesture detector onDrag callback

---

lib/src/modal_type/wolt_alert_dialog_type.dart
lib/src/modal_type/wolt_dialog_type.dart
lib/src/wolt_modal_sheet.dart
playground/lib/home/home_screen.dart

The `modalDecorator` in `WoltModalSheet` was not correctly wrapping the modal content, causing inherited widgets or providers added via modalDecorator to be inaccessible within `pageListBuilder`. This resulted in exceptions like `ProviderNotFoundException` when attempting to access context-dependent widgets inside pageListBuilder.
Wolt internal problem.
The fix involves adjusting the build process in WoltModalSheet to ensure that the `modalDecorator` is applied before `pageListBuilder` is called. This way, the `context` used within `pageListBuilder` includes the inherited widgets or providers added by modalDecorator.
1. Modified the build Method in WoltModalSheetState:
- Checked if a `modalDecorator` is provided.
- If so, wrapped the modal content with `modalDecorator` using a `Builder` …

Fix modalDecorator Context Wrapping in WoltModalSheet

---

.github/workflows/checks.yml
.github/workflows/firebase-hosting-pull-request.yml
analysis_options.yaml
coffee_maker/pubspec.yaml
coffee_maker_navigator_2/pubspec.yaml
demo_ui_components/pubspec.yaml
example/pubspec.yaml
melos.yaml
playground/pubspec.yaml
playground_navigator2/lib/router/playground_router_delegate.dart
playground_navigator2/lib/router/router_pages/home_page.dart
playground_navigator2/lib/router/router_pages/sheet_page.dart
playground_navigator2/lib/router/router_pages/unknown_page.dart
playground_navigator2/pubspec.yaml
pubspec.yaml
test/wolt_modal_sheet_test.dart

Bumps the min Flutter SDK version to 3.16.0

Bump min Flutter SDK version to 3.16.0

---

README.md

Works around https://github.com/woltapp/wolt_modal_sheet/issues/358
This removes the popularity badge, since neither https://badgen.net/ nor https://shields.io/ support the download metric yet.

Remove popularity badge

---

lib/src/widgets/wolt_navigation_toolbar.dart
test/widgets/wolt_navigation_toolbar_test.dart

Fixes [leadingNavBarWidget uses more vertical space than trailingNavBarWidget](https://github.com/woltapp/wolt_modal_sheet/issues/360)
<details>
<summary>expand to view the code sample</summary> 
```dart
import 'package:flutter/material.dart';
import 'package:wolt_modal_sheet/wolt_modal_sheet.dart';
void main() {
runApp(const MyApp());
}
class MyApp extends StatelessWidget {
const MyApp({super.key});
@override
Widget build(BuildContext context) {
return MaterialApp(
home: Builder(builder: (context) {
return Scaffold(
body: Center(
child: TextButton(
child: const Text('Open WoltModalSheet'),
onPressed: () {
WoltModalSheet.show(
context: context,
pageListBuilder: (context) => [
WoltModalSheetPage(
isTopBarLayerAlwaysVisible: true,
topBarTitle: const Text('Title'),
leadingNavBarWidget: …
```

Fix `WoltNavigationToolbar` leading constraint

---

lib/src/widgets/wolt_modal_sheet_drag_to_dismiss_detector.dart

Fixes an issue where Hero widgets fail to animate properly when drag-dismissing a WoltModalSheet that reaches a near-zero position. Previously, when dragging the sheet to a position very close to zero and releasing, the Hero widgets on the underlying route would not animate back correctly, while they worked fine when drag-dismissing from halfway or using fling gestures.
The fix prevents the animation controller from reaching a fully dismissed state during drag operations by implementing a minimum threshold of 0.01. This ensures the proper dismissal sequence is always followed, allowing Hero widgets to complete their transitions correctly.
Changes:
- Added minimum threshold check in vertical and horizontal drag update handlers
- Ensures consistent Hero widget behavior across all dismissal …

Fix Hero animation when drag-dismissing WoltModalSheet at zero threshold
