woltapp/wolt_modal_sheet

pubspec.yaml
I have fixed the link in pubspc.yaml.
=> Fix repository link

README.md
Ths PR adds the link to the recording of the talk about this package to the Readme.
=> Add FlutterCon talk link to the ReadMe additional information

README.md
This PR adds the recording of the Flutter&Friends talk related to the usage of this package to the ReadMe.
=> Add the Flutter&Friends talk to the additional information section

.github/workflows/check.yml, lib/src/content/wolt_modal_sheet_layout.dart, playground/lib/main.dart
fixes [Add Pull Request checks](https://github.com/woltapp/wolt_modal_sheet/issues/83) 
This PR adds a `flutter analyze` check to be run on PRs.
At the moment in the `main` there are 3 analyzer issues and i didn't fix them, this is intentional so we can test PR check is working in the follow-up PRs.
=> Add `flutter analyze` check

README.md
=> Chore: add badges to README.md

.github/ISSUE_TEMPLATE/1_bug_report.md, .github/ISSUE_TEMPLATE/2_feature_request.md
This PR adds feature request and issue templates to the repo so that we can see and handle incoming tickets better.
Heavily inspired by [flutterfire](https://github.com/firebase/flutterfire) and [flutter](https://github.com/flutter/flutter) templates 💙 
https://github.com/orgs/woltapp/projects/1/views/1?pane=issue&itemId=39806966
=> Add feature request and issue templates

CHANGELOG.md, pubspec.yaml
Update CHANGELOG.md for changes and bump version
=> Prepare v0.2.0

CHANGELOG.md, pubspec.yaml
=> Prepare v0.3.0

CHANGELOG.md, pubspec.yaml
Bump to 0.4.0 and update ChangeLog
=> Prepare 0.4.0

README.md
This PR introduces "Table of Contents" to the `README.md` file
fixes [Include a "Table of Contents" in README](https://github.com/woltapp/wolt_modal_sheet/issues/174)
=> Add "Table of Contents" to `README.md`

lib/src/wolt_modal_sheet.dart
Expose page index getter, fixes https://github.com/woltapp/wolt_modal_sheet/issues/202
=> Expose Page index getter

lib/src/wolt_modal_sheet.dart
⚒️ WIP
```
⚠️ The Playground Example has been re-built using this added router, check it out!
```
This PR adds a page router, page routes and page controllers.
It's API allows for designing reusable, composable pages.
All routing is handled automatically. You can also push and pop results from individual pages.
This all uses `showWithDynamicPath` under the hood. No changes were made to existing code
This is still needs tests and docs.
I'm open to any changes on the API design.
I've added a router that handles all navigation:
```dart
// Router with initial routes
final router = WoltModalSheetPageRouter([RootPage()]); 
// Push it
WoltModalSheet.showWithRouter(
context: context,
router: router,
);
```
You can also go directly into child pages by using multiple routes:
```dart
// Router that …
```
=> Add Controller

test/wolt_modal_sheet_test.dart
Related to [Prepare repository for tests requirement](https://github.com/woltapp/wolt_modal_sheet/issues/211)
=> Update `wolt_modal_sheet_test.dart` tests

.github/workflows/checks.yml, .github/workflows/firebase-hosting-pull-request.yml, playground_navigator2/lib/router/playground_route_information_parser.dart, pubspec.yaml
According to last 4 stable version support rule, we are bumping the min supported Flutter SDK version to 3.13.0.
=> Bump min supported Flutter version to 3.13.0

CHANGELOG.md, pubspec.yaml
Hotfix release including https://github.com/woltapp/wolt_modal_sheet/issues/226
=> Prepare 0.6.1

lib/src/modal_type/wolt_alert_dialog_type.dart, lib/src/modal_type/wolt_bottom_sheet_type.dart, lib/src/modal_type/wolt_dialog_type.dart, lib/src/modal_type/wolt_side_sheet_type.dart
This PR fix the modal type enter/exit animations
=> Fix: Updated enter/exit animations for modal types

CHANGELOG.md, pubspec.yaml
Prepare 0.7.0 release. I also added the information of the person who contributed. If it is not okay, l can remove it.
=> Prepare 0.7.0 release

README.md
Added Last Commit badge to readme
| ![Screenshot 2024-07-08 at 00 26 10](https://github.com/woltapp/wolt_modal_sheet/assets/13484562/96ca7589-9494-447e-8c36-213bddaa07b8) | ![Screenshot 2024-07-08 at 00 25 51](https://github.com/woltapp/wolt_modal_sheet/assets/13484562/c7d8642d-d9ff-41b6-83a5-07c53dc7e5d9) |
[Add Last Commit badge to Readme](https://github.com/woltapp/wolt_modal_sheet/issues/256)
=> Adjustment: Add Last Commit badge to readme

CHANGELOG.md, pubspec.yaml
=> Prepare 0.7.1 release

CHANGELOG.md, README.md, pubspec.yaml
=> Prepare 0.8.0 release

CHANGELOG.md, pubspec.yaml
=> Prepare 0.9.0 release

CHANGELOG.md, pubspec.yaml
=> Preapre 0.9.1

test/wolt_modal_sheet_test.dart
Related [Prepare repository for tests requirement](https://github.com/woltapp/wolt_modal_sheet/issues/211)
=> Add tests custom  `modalTypeBuilder`, `modalDecorator`, `pageContentDecorator`, and restructure the test class

coffee_maker_navigator_2/lib/main.dart
Added the following diagram to explain the wolt_di framework in main.dart.
```dart
/*
+----------------------------------+
|  DependencyContainerManager      |       +----------------------------------+
|  +-----------------------------+ |       |                                  |
|  | App Level DI Container      | |       |          MaterialApp             |
|  | +-------------------------+ | |       |  +-----------------------------+ |
|  | | AuthService             | | |       |  |    DependencyInjector       | |
|  | +-------------------------+ | |       |  |          Widget             | |
|  | | AuthRepository          | | |       |  |  +-----------------------+  | |
|  | +-------------------------+ | |       |  |  | FeatureLevelDependency|  | |
|  | | AuthRemoteDataSource    | | | …
```
=> [Coffee Maker Demo app] Added dependency injection explanation in code diagram to main.dart

coffee_maker_navigator_2/lib/features/orders/di/orders_dependency_container.dart, coffee_maker_navigator_2/lib/features/orders/ui/view/widgets/order_screen_content.dart, coffee_maker_navigator_2/lib/features/orders/ui/view/widgets/orders_screen_bottom_navigation_bar.dart, coffee_maker_navigator_2/lib/features/orders/ui/view_model/orders_screen_view_model.dart, coffee_maker_navigator_2/pubspec.yaml, coffee_maker_navigator_2/widgetbook/lib/src/features/orders/view/widgets/orders_screen_bottom_navigation_bar.dart, coffee_maker_navigator_2/widgetbook/lib/src/features/orders/view/widgets/orders_screen_content.dart, coffee_maker_navigator_2/widgetbook/pubspec.yaml, melos.yaml, wolt_state_management/README.md, wolt_state_management/lib/src/stateful_value_listenable_builder.dart, wolt_state_management/lib/src/stateful_value_notifier.dart, wolt_state_management/lib/src/value_state.dart, wolt_state_management/lib/test/stateful_value_listenable_builder_test.dart, wolt_state_management/lib/test/stateful_value_notifier_test.dart, wolt_state_management/lib/test/value_state_test.dart, wolt_state_management/lib/wolt_state_management.dart, wolt_state_management/pubspec.yaml
=> State management experiements for demo app

README.md, examples/playground/lib/home/pages/custom_sheet_pages/product_with_sku_page.dart, examples/playground/lib/home/pages/root_sheet_page.dart, examples/playground/lib/home/pages/sheet_page_with_in_app_navigation.dart, lib/src/wolt_modal_sheet.dart
Implements the navigation method described in #346. I added example usage but did not check whether test still work. 
- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
=> Show page with type and selector

CHANGELOG.md, pubspec.yaml
=> Prepare 0.10.0

.github/workflows/widgetbook.yml
Added Widgetbook cloud action
*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/woltapp/wolt_modal_sheet/issues). Indicate, which of these issues are resolved or fixed by this PR.*
=> Add workflow

CHANGELOG.md, pubspec.yaml
- Changelog updated
- Bumped version to 0.11.0
=> Prepare release 0.11.0
